### ISSUE TITLE
androidx.test support

### ISSUE THREAD

**Issue by kylpo** [Zhuinden/espresso-helper#10]
I'm seeing "Cannot access class 'android.support.espresso.'" in my new project which uses androidx.

Do you plan to support a branch with the androidx imports while it is pre-stable? Or should I keep a personal fork with this for now?

Thanks for the lib!

**Comment by Zhuinden** [comment]
```
com.android.support.test.espresso:espresso-contrib | androidx.test.espresso:espresso-contrib:3.1.0-alpha1
com.android.support.test.espresso:espresso-core | androidx.test.espresso:espresso-core:3.1.0-alpha1
```

I'm publishing via Jitpack so managing two different versions would be tricky.

I'm actually also slightly unsure how well the Jetifier will or will not handle this, so I intend to swap the `api` deps out for `androidx` (espresso 3.1.0) only when they're stable.

Luckily, this lib consists of a total of 3 files at this time, so forking it shouldn't be too difficult :slightly_smiling_face: 

>  Or should I keep a personal fork with this for now?

That's what I recommend at this time

**Comment by kylpo** [comment]
Got it - sounds good. Just wanted to ask before I forked it.

Thanks!

**Comment by Zhuinden** [comment]
It's probably super-obsolete by now, but it was done in https://github.com/Zhuinden/espresso-helper/commit/952c05644e13a22bd0cb06e0795f5b9cee5a2e28
