### ISSUE TITLE
Tests for each functionality

### ISSUE THREAD

**Issue by xgleich1** [Zhuinden/espresso-helper#8]
First of all a big thanks for your work on this lib, it looks really helpful! 

Bit I am hesitant to use it since there are almost no tests in this project (the simple one in the sample project is not enough) and thus no way to verify that your code works as intendet. 

This would also serve as a great way to showcase your complete api.

**Comment by Zhuinden** [comment]
Completely agree! Lot of the code is based on agoda/kakao, but tests would be nice nonetheless :+1:

**Comment by aumarbello** [comment]
Interested in taking this up, but could explain the nature of the tests that should be written?

**Comment by Zhuinden** [comment]
@aumarbello technically there are a bunch of assertion types that start with `check___`, technically [this block of code](https://github.com/Zhuinden/espresso-helper/blob/29d79eb0777397e49281d877b27968a2c2678740/espresso-helper/src/main/java/com/zhuinden/espressohelper/EspressoHelper.kt#L527-L821)


For example, for `checkContainsText`, you'd need a text view that has a given text, and you would need to verify that if the TextView contains the right text then there is no assertion error, but if the TextView contains the wrong text then an assertion error is thrown.

This would be required for each `check___` assertion type, but just adding *any* of such tests would be helpful.

Evidently, this would have to be done in instrumentation test.

**Comment by aumarbello** [comment]
Okay, so for example if I want to test all the assertions that have to do with texts I will need an activity with TextView and in the activity's instrumentation test after using the assertions, verify the behavior (happy and sad path) of the assertions I used right?

**Comment by Zhuinden** [comment]
Yep!

**Comment by aumarbello** [comment]
Okay, would love to work on the full suites of tests but would it be okay to do so gradually?

**Comment by Zhuinden** [comment]
I mean, it'd be crazy if I expected immediate 100% completion, I'm already glad someone volunteers for any of it in the first place.

Totally ok to do it gradually, of course. Happy to have help in general. :smile:

**Comment by aumarbello** [comment]
Okay, would get started on it.

**Comment by Zhuinden** [comment]
Thanks!
